### ISSUE TITLE
Error in github actions with return: cannot find module 'strip-indent

### ISSUE THREAD

**Issue by RUANDUARTE03** [testing-library/react-testing-library#1021]
## Error in github action

This is my workflow

```
name: UnitTests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Prepare cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install node-sass
        run: npm i node-sass

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

```

When run tests action is executed, this error is returned

![image](https://user-images.githubusercontent.com/53544158/156295168-a9d7caad-c3c1-462d-94d9-d450163268ec.png)

Add `npx browserslist@latest --update-db`, but error

My package is this
```
"test": "jest --silent",
"test:ci": "npm run test",
"@testing-library/jest-dom": "^5.15.1",
"@testing-library/react": "^12.1.2",
"@testing-library/user-event": "^13.5.0",
```

I need suport, please
